#!/bin/sh


if [ -f $HOME/.colors.h ]; then
  eval `/bin/grep '^#define' $HOME/.colors.h | /bin/sed 's/#define[[:space:]]*\([^ ]*\)[[:space:]]*\(.*\)/\1=\2;export \1;/'`
fi

xrdb -I$HOME -load $HOME/.Xdefaults.xsession

xloadimage -onroot $HOME/desktop.jpg &

xterm &

export TRIMFG="red"
export TRIMBG="black"

xrdb -I$HOME -load $HOME/.Xdefaults

xscreensaver &

eval `ssh-agent`

# syndaemon disables the touchpad for a short period of time after
# keypresses to avoid accidental input
which syndaemon && syndaemon -S -t -i 1 -d

fvwm2
