#!/bin/bash

set -x


if [ -f $HOME/.colors.h ]; then
  eval `/bin/grep '^#define' $HOME/.colors.h | /bin/sed 's/#define[[:space:]]*\([^ ]*\)[[:space:]]*\(.*\)/\1=\2;export \1;/'`
fi

xrdb -I$HOME -load $HOME/.Xdefaults.xsession

xloadimage -onroot $HOME/desktop.jpg &

xterm &

export TRIMFG="red"
export TRIMBG="black"

xrdb -I$HOME -load $HOME/.Xdefaults

eval `ssh-agent`
gtk-redshift -l 37.8:-122 &

export WINDOW_MANAGER=/usr/bin/fvwm2 
exec gnome-session --session=fvwm
