;; dark color for xemacs
;; append it to .emacs file, remove other custom-set-faces
;; by Gang Zou
(custom-set-faces
 '(default ((t (:foreground "gray90" :background "gray10"))) t)
 '(text-cursor ((t (:foreground "gray70" :background "red"))) t)
 '(secondary-selection ((t (:background "#008b8b"))) t)
 '(widget-field-face ((((class grayscale color) (background light)) (:background "gray25"))) t)
 '(font-lock-string-face ((((class color) (background light)) (:foreground "#90ee90"))) t)
 '(font-lock-reference-face ((((class color) (background light)) (:foreground "red"))) t)
 '(widget-documentation-face ((((class color) (background light)) (:foreground "#90ee90"))) t)
 '(custom-group-tag-face ((((class color) (background light)) (:foreground "#87cefa" :underline t))) t)
 '(custom-variable-tag-face ((((class color) (background light)) (:foreground "#87cefa" :underline t))) t)
 '(font-lock-doc-string-face ((((class color) (background light)) (:foreground "#90ee90"))) t)
 '(font-lock-preprocessor-face ((((class color) (background light)) (:foreground "#00ced1"))) t)
 '(font-lock-variable-name-face ((((class color) (background light)) (:foreground "plum1"))) t)
 '(custom-state-face ((((class color) (background light)) (:foreground "#90ee90"))) t)
 '(font-lock-keyword-face ((((class color) (background light)) (:foreground "#ffb90f"))) t)
 '(font-lock-type-face ((((class color) (background light)) (:foreground "cyan2"))) t)
 '(widget-inactive-face ((((class grayscale color) (background light)) (:foreground "gray60"))) t)
 '(primary-selection ((t (:background "gray40"))) t)
 '(list-mode-item-selected ((t (:background "gray32"))) t)
 '(font-lock-comment-face ((((class color) (background light)) (:foreground "#b0e0e6"))) t)
 '(font-lock-function-name-face ((((class color) (background light)) (:foreground "#eeb4b4"))) t)
 '(isearch ((t (:background "#008b8b"))) t)
 '(highlight ((t (:background "#556b2f"))) t)
 '(zmacs-region ((t (:background "gray45"))) t))
